config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users

  #companies controller
  get 'show_companies', to: 'companies#index', as: 'companies'  
  get '/companies', to: 'companies#companies', as: 'companies_report'

  #tasks controller
 
  post 'tasks/save_time', to: 'tasks#save_time', as: 'save_time'
  get '/', to: 'tasks#my_tasks', as: 'my_tasks'
  post '/', to: 'tasks#my_tasks', as: 'my_tasks_post'
  get '/complete_task/:id', to: 'tasks#complete_task', as: 'complete_task'
  get '/activate_task/:id', to: 'tasks#activate_task', as: 'activate_task'
  post '/task/update_task_time_spent', to: 'tasks#update_task_time_spent', as: 'update_task_time_spent'

  #users
  get 'show_user/:id', to: 'users#show_user', as: 'show_user'

  #admin tasks
  get '/admin/tasks', to: 'admin#tasks', as: 'admin_tasks'
  post '/admin/tasks/create', to: 'admin#create_task', as: 'admin_create_task'
  get '/admin/delete_task/:id', to: 'admin#destroy_task', as: 'admin_delete_task'
  get '/admin/new_task', to: 'admin#new_task', as: 'admin_new_task'  
  get 'tasks/:id', to: 'admin#show_task', as: 'admin_show_task'
  get '/admin/recreate_tasks', to: 'admin#recreate_tasks', as: 'recreate_tasks'


  #admin companies
  get '/admin/companies', to: 'admin#companies', as: 'admin_companies'
  get '/admin/new_company', to: 'admin#new_company', as: 'new_company'
  post '/admin/create_company', to: 'admin#create_company', as: 'create_company'
  get '/admin/show_company/:id', to: 'admin#show_company', as: 'company'
  get '/admin/edit_company/:id', to: 'admin#edit_company', as: 'edit_company'
  post '/admin/update_company', to: 'admin#update_company', as: 'update_company'
  get '/admin/delete_company/:id', to: 'admin#destroy_company', as: 'delete_company'


end

app/views/admin/companies.html.erb
<div class="container"> 
<h2>Companies</h2>

<% @companies.each do |company| %>
  <li>
    <h3><%= link_to company.name.capitalize, company_path(company.id) %>
      <%= link_to "Edit Company", edit_company_url(company.id), :class => 'btn btn-primary' %>
       <%= link_to "Delete Company", delete_company_path(company.id), class: 'btn btn-danger' %>
     </h3>
   </li>
<% end %>
</br>
<%= link_to "New Company", new_company_path, :class => 'btn btn-primary' %>

</div>

app/views/admin/edit_company.html.erb
<div class="container">
<h1>Edit Company</h1>
 <div class="col-sm-4">
 <%= form_for @company, url: update_company_path, method: 'POST' do |f| %>
    <%= f.hidden_field :id %>
   <div class="form-group"> 
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter name" %>
   </div>
  
    <%= f.collection_select :user_id, @users.all, :id, :email %>
  <div class="clear"></div>
  </br>
  <div class="clear"></div>
  <%= f.submit "Update company", class: 'btn btn-primary' %>
 <% end %>
 </div>
</div>

app/views/admin/new_company.html.erb
<% @new_company_name = flash[:new_company_name] %>
<div class="container"> 
<h1>New Company</h1>
 <div class="col-sm-4">
 <%= form_for Company.new, :method => 'POST', url: create_company_path do |f| %>
   <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, value: @new_company_name,class: 'form-control', placeholder: "Enter name" %>
   </div>
   <div class="form-group">
    <%= f.collection_select :user_id, @users.all, :id, :email %>
   </div>
  <%= f.submit "Save company", class: 'btn btn-success' %>
 <% end %>
 </div>
</div>

app/views/admin/new_task.html.erb
<% @new_task_title = flash[:new_task_title] %>
<% @new_task_recreate_task_days = flash[:new_task_recreate_task_days] %>
<div class="container"> 
 <h1>New Task</h1>
 <div class="col-sm-4">
  <%= form_for :anything, :method => 'POST', :class => 'form-inline', url: admin_create_task_path do |f| %>

  <div class="form-group">
    <%= f.select :company_id, options_for_select(Company.all.collect { | user | [user.name, user.id] }, 1), {}, {} %>
  </div>
   <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, value: @new_task_title, class: 'form-control', placeholder: "Enter title" %>
   </div>

   <div class="form-group"> 
    <%= f.label :recreate_task_days %>
    <%= f.text_field :recreate_task_days, value: @new_task_recreate_task_days, class: 'form-control', placeholder: "Enter days" %>
   </div>

    <%= f.submit "Save task", class: 'btn btn-success' %>
  <% end %>
 </div>
</div>

app/views/admin/show_company.html.erb
<div class="container">
<h1><%= @company.name %></h1>
User email: <%= User.convert_id_to_email(@company.user_id) %></br>
<h2>Tasks</h2>
<ol>
<% for @task in @tasks %>
  <li><%= @task.title%></li>
<% end %>
</ol>
</br>
<%= link_to "New task", admin_new_task_path, :class => 'btn btn-success'%>

</div>
<div class="clear"></div>
</br>
<div class="clear"></div>
<div class="container">
  <%= link_to "Delete Company", @company, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this company?'} %>
</div>

app/views/admin/show_task.html.erb
Show task <%= @task.id%>

app/views/admin/tasks.html.erb
<div class="container">
  <h1>All Tasks&nbsp;<%= link_to "New task", admin_new_task_path, :class => "btn btn-success btn-sm"%>&nbsp;<%= link_to "Recreate tasks", recreate_tasks_path, :class => "btn btn-primary btn-sm", :style => 'font-color:white;'%>
</h1>
</div>
</br>
<div class="clear"></div>
</br>
 <div class="col-sm-12">
<%= grid(@tasks_grid, show_filters: :always, upper_pagination_panel: true) do |g|
   g.column name: 'ID', attribute: 'id'   
   g.column name: 'Task', attribute: 'title' do |task|
     link_to(task.title, admin_show_task_path(task.id))
   end
   g.column name: 'Company', assoc: :company, attribute: 'name', custom_filter: @hash_companies, auto_reload: true do |task|
    link_to(task.company.name, company_path(task.company.id)) if task.company
   end
   
   g.column name: 'User', assoc: :user, attribute: 'email', custom_filter: @hash_users, auto_reload: true do |task|
    link_to(task.user.email, user_path(task.user.id)) if task.user
   end

  g.column name:  'Archived', attribute: 'archived', auto_reload:  true  do |task|
    task.archived? ? 'yes' : 'no'
  end
  g.column name: 'Date Created', attribute: 'created_at' do |task|
     task.created_at.to_date
   end
  g.column name: 'Recreate task days', attribute: 'recreate_task_days'
  g.column name: 'Archive' do |task|
    if task.archived == false then  
     link_to('Archive', admin_delete_task_path(task.id), :class => 'btn btn-danger btn-sm')
    else
     link_to('Un-archive', admin_delete_task_path(task.id), :class => 'btn btn-danger btn-sm')
    end
  end
  g.column name: 'Time spent(minutes)', attribute: 'time' do |task|
     if task.time then link_to(task.time, update_task_time_spent_path(task.time), :class => 'editable_time', :data => { :type => 'text', :pk => task.id, :url => update_task_time_spent_path}) 
     else
       link_to("0", update_task_time_spent_path(task.time), :class => 'editable_time', :data => { :type => 'text', :pk => task.id, :url => update_task_time_spent_path}) 
     end
  end
 end %>
</div>

<script>
  $.fn.editable.defaults.mode = 'inline';
  
  $(document).ready(function() {
   $('.editable_time').editable();
  });


  $("#li_tasks").addClass('active');

 $("#save_time").click(function(){
   var task_id = String($("#task_id").val()); //parent().parent().parent().children().first()
   var time_value = String($("#time_value").val());
   if(task_id != "" && time_value != ""){
   $.post('/tasks/save_time', {time: time_value, task_id: task_id}, function(){
     alert('time added!');
   });
   }

 });

</script>