config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users

  #companies controller
  get 'show_companies', to: 'companies#index', as: 'companies'  
  get '/companies', to: 'companies#companies', as: 'companies_report'

  #tasks controller
 
  post 'tasks/save_time', to: 'tasks#save_time', as: 'save_time'
  get '/', to: 'tasks#my_tasks', as: 'my_tasks'
  post '/', to: 'tasks#my_tasks', as: 'my_tasks_post'
  get '/complete_task/:id', to: 'tasks#complete_task', as: 'complete_task'
  get '/activate_task/:id', to: 'tasks#activate_task', as: 'activate_task'
  post '/task/update_task_time_spent', to: 'tasks#update_task_time_spent', as: 'update_task_time_spent'

  #users
  get 'show_user/:id', to: 'users#show_user', as: 'show_user'

  #admin tasks
  get '/admin/tasks', to: 'admin#tasks', as: 'admin_tasks'
  post '/admin/tasks/create', to: 'admin#create_task', as: 'admin_create_task'
  get '/admin/delete_task/:id', to: 'admin#destroy_task', as: 'admin_delete_task'
  get '/admin/new_task', to: 'admin#new_task', as: 'admin_new_task'  
  get 'tasks/:id', to: 'admin#show_task', as: 'admin_show_task'
  get '/admin/recreate_tasks', to: 'admin#recreate_tasks', as: 'recreate_tasks'


  #admin companies
  get '/admin/companies', to: 'admin#companies', as: 'admin_companies'
  get '/admin/new_company', to: 'admin#new_company', as: 'new_company'
  post '/admin/create_company', to: 'admin#create_company', as: 'create_company'
  get '/admin/show_company/:id', to: 'admin#show_company', as: 'company'
  get '/admin/edit_company/:id', to: 'admin#edit_company', as: 'edit_company'
  post '/admin/update_company', to: 'admin#update_company', as: 'update_company'
  get '/admin/delete_company/:id', to: 'admin#destroy_company', as: 'delete_company'


end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :tasks
  belongs_to :user

  def self.save_company_errors(params, current_user)
    @errors = ""
    @name = params["company"]["name"]
    if current_user == nil then @errors += "No logged in user."
    elsif @name == "" then @errors += "Company name is empty."
    end
    if @name != "" then 
      @company = Company.find_by_name(@name)
      if @company != nil then 
        @errors += "Company name already exists."
      end
    end
    return @errors
  end

  def self.save_company(params, user_id)
    @company = Company.new
    @company.name = params["company"]["name"]
    @company.user = user_id
    @company.save
  end

  def self.update_company_errors(params)
    @errors = ""
    @company = Company.find_by_id(params["company"]["id"])
    @name = params["company"]["name"]
    @user_id = params["company"]["user_id"]
    if @company == nil then @errors += "Company not found."
    elsif @name == "" then @errors += "Company name is empty."
    elsif @user_id == "" then @errors += "User ID is empty."
    end
    return @errors
  end

  def self.update_company(params)
    @company = Company.find_by_id(params["company"]["id"])
    @company.name = params["company"]["name"]
    @company.user_id = params["company"]["user_id"]
    @company.save
  end

  def self.destroy_company(company)
    Task.where(:company_id => company.id).destroy_all
    company.destroy
  end

  def self.generate_random_companies(n)
    ActiveRecord::Base.connection.execute("delete from companies")
    @user_ids = User.all.pluck(:id)
    ActiveRecord::Base.transaction do
     for @i in (1..n.to_i) do
       Company.create!(name: Faker::Company.name, user_id: @user_ids.sample.to_i)
     end
    end
    puts n.to_s + " random companies have been generated."
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :authenticate_user!
  before_action :require_admin

  private 

  def require_admin
    #puts "Current user: " + current_user.role.to_s
    if current_user.role.to_s != "admin" then      
      flash[:notice] = "Admin required to view companies."
      redirect_to root_path
    end
  end

  public

  def index
    @companies = Company.all
  end

  
  def companies
    @companies_grid = initialize_grid(Company)

  end

end

app/helpers/companys_helper.rb
module CompanysHelper
  def add_task_link(name)
    link_to name do |page|
      page.insert_html :bottom, :tasks, :partial => 'task', :object => Task.new
    end
  end
end

app/views/companies/companies.html.erb
    <script>
        window.onload = function() {
            var timer = new Tock({
                callback: function () {
                    $('#clockface').val(timer.msToTime(timer.lap()));
                }
            });
            $('#start').on('click', function () {
                timer.start($('#clockface').val());
            });
            $('#lap').on('click', function () {
                $('#laptimes').append(timer.msToTime(timer.lap()) + '<br>');
            });
            $('#pause').on('click', function () {
                timer.pause();
            });
            $('#stop').on('click', function () {
                timer.stop();
            });
            $('#reset').on('click', function () {
                timer.reset();
                $('#clockface').val('');
                $('#laptimes').html('');
            });
            var countdown = Tock({
                countdown: true,
                interval: 250,
                callback: function () {
                    console.log(countdown.lap() / 1000);
                    $('#countdown_clock').val(timer.msToTime(countdown.lap()));
                },
                complete: function () {
                    console.log('end');
                    alert("Time's up!");
                }
            });
            $('#startCountdown').on('click', function () {
                countdown.start($('#countdown_clock').val());
            });
            $('#pauseCountdown').on('click', function () {
                countdown.pause();
            });
            $('#stopCountdown').on('click', function () {
                countdown.stop();
            });
            $('#resetCountdown').on('click', function () {
                countdown.stop();
                $('#countdown_clock').val('00:02');
            });
        }
    </script>
<div class="container">
  <h1>All companies&nbsp;<%= link_to "New company", new_company_path, :class => "btn btn-success btn-sm"%>&nbsp;</h1>
</div>
</br>
<div class="clear"></div>
</br>
 <div class="col-sm-12">
<%= grid(@companies_grid, show_filters: :always, upper_pagination_panel: true) do |g|
   g.column name: 'ID', attribute: 'id'   
   g.column name: 'Name', attribute: 'name'
   g.column name: 'User id', attribute: 'user_id'
   g.column name: 'Date Created', attribute: 'created_at' do |task|
     task.created_at.to_date
   end
   g.column name: 'Edit' do |company|
     link_to('Show', company_path(company.id), :class => 'btn btn-warning btn-sm')
   end
   g.column name: 'Edit' do |company|
     link_to('Edit', edit_company_path(company.id), :class => 'btn btn-primary btn-sm')
   end
   g.column name: 'Delete' do |company|
     link_to('Delete', delete_company_path(company.id), :class => 'btn btn-danger btn-sm')
   end
 end %>
</div>
</br></br></br>
<script>
  
  $("#li_companies").addClass('active');


 $("#save_time").click(function(){
   var task_id = String($("#task_id").val()); //parent().parent().parent().children().first()
   var time_value = String($("#time_value").val());
   if(task_id != "" && time_value != ""){
   $.post('/tasks/save_time', {time: time_value, task_id: task_id});
   }

 });

</script>

app/views/companies/index.html.erb
<div class="container"> 
<h2>Companies</h2>

<% @companies.each do |company| %>
  <li>
    <h3><%= link_to company.name.capitalize, company_path(company.id) %>
      <%= link_to "Edit Company", edit_company_url(company.id), :class => 'btn btn-primary' %>
       <%= link_to "Delete Company", delete_company_path(company.id), class: 'btn btn-danger' %>
     </h3>
   </li>
<% end %>
</br>
<%= link_to "New Company", new_company_path, :class => 'btn btn-primary' %>

</div>