config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users

  #companies controller
  get 'show_companies', to: 'companies#index', as: 'companies'  
  get '/companies', to: 'companies#companies', as: 'companies_report'

  #tasks controller
 
  post 'tasks/save_time', to: 'tasks#save_time', as: 'save_time'
  get '/', to: 'tasks#my_tasks', as: 'my_tasks'
  post '/', to: 'tasks#my_tasks', as: 'my_tasks_post'
  get '/complete_task/:id', to: 'tasks#complete_task', as: 'complete_task'
  get '/activate_task/:id', to: 'tasks#activate_task', as: 'activate_task'
  post '/task/update_task_time_spent', to: 'tasks#update_task_time_spent', as: 'update_task_time_spent'

  #users
  get 'show_user/:id', to: 'users#show_user', as: 'show_user'

  #admin tasks
  get '/admin/tasks', to: 'admin#tasks', as: 'admin_tasks'
  post '/admin/tasks/create', to: 'admin#create_task', as: 'admin_create_task'
  get '/admin/delete_task/:id', to: 'admin#destroy_task', as: 'admin_delete_task'
  get '/admin/new_task', to: 'admin#new_task', as: 'admin_new_task'  
  get 'tasks/:id', to: 'admin#show_task', as: 'admin_show_task'
  get '/admin/recreate_tasks', to: 'admin#recreate_tasks', as: 'recreate_tasks'


  #admin companies
  get '/admin/companies', to: 'admin#companies', as: 'admin_companies'
  get '/admin/new_company', to: 'admin#new_company', as: 'new_company'
  post '/admin/create_company', to: 'admin#create_company', as: 'create_company'
  get '/admin/show_company/:id', to: 'admin#show_company', as: 'company'
  get '/admin/edit_company/:id', to: 'admin#edit_company', as: 'edit_company'
  post '/admin/update_company', to: 'admin#update_company', as: 'update_company'
  get '/admin/delete_company/:id', to: 'admin#destroy_company', as: 'delete_company'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">BCB Tasks</a>
    </div>
    <ul class="nav navbar-nav">
    <% if current_user != nil then %>
     <% if current_user.role.to_s == "admin" then %>
      <li id="li_home" class="li_active"><a href="/">Home</a></li>
      <li id="li_tasks" class="li_active"><%= link_to "Tasks", admin_tasks_path %></li>     
      <li id="li_companies" class="li_active"><%= link_to "Companies", companies_report_path %></li>  
     <% end %> 
    <% end %>     
    </ul>
    <ul class="nav navbar-nav" style="float:right;">
      <% if user_signed_in? %>
       <li id="li_show_user" class="li_active"><%= link_to current_user.email, show_user_path(current_user.id) %></li>        
       <li id="li_edit_profile" class="li_active"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'float_right' %></li>
       <li class="li_active"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'float_right'  %></li>
      <% else %>        
       <li class="li_active"><%= link_to "Sign Up", new_user_registration_path, :class => 'float_right'  %></li>
       <li class="li_active"><%= link_to "Sign In", new_user_session_path, :class => 'float_right'  %></li>
      <% end %>
    </ul>
   </div>
  </nav>   
     <% if flash[:notice] != nil%>
       <div class="alert alert-success col-sm-4">
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning col-sm-4">
         <%= flash[:alert] %>
       </div>
     <% end %>
<div class="clear"></div>
<%= yield %>
<script>
  $("#error_explanation>h2").hide();

</script>
</body>
</html>